# Generated by Django 3.2.2 on 2021-05-15 04:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210515_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='entry_id',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='categories',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
