# Generated by Django 3.2.2 on 2021-05-15 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210515_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 5, 15, 12, 6, 48, 39526, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_desc',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
