# Generated by Django 3.2.2 on 2021-05-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20210515_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_published',
        ),
    ]
