# Generated by Django 3.2.2 on 2021-05-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_desc',
            field=models.CharField(max_length=255),
        ),
    ]
