# Generated by Django 3.2.2 on 2021-05-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_alter_posts_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='publication_date',
            field=models.DateTimeField(verbose_name='Published'),
        ),
    ]
