# Generated by Django 3.2.2 on 2021-05-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_alter_posts_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category_desc',
            new_name='category_description',
        ),
    ]
