# Generated by Django 3.2.2 on 2021-05-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_rename_category_desc_categories_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=2),
        ),
    ]
