# Generated by Django 3.2.2 on 2021-05-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_categories_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Female', max_length=2),
        ),
    ]
