# Generated by Django 3.2.2 on 2021-05-29 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_auto_20210529_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_desc',
            field=models.TextField(default=datetime.datetime(2021, 5, 29, 16, 59, 51, 686857, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
