# Generated by Django 3.2.2 on 2021-05-29 17:37

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_auto_20210529_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='Media/profile_pics'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user',
            field=models.CharField(max_length=100, verbose_name=django.contrib.auth.models.User),
        ),
    ]
